name: cache_5
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image with Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      # - name: Cache Docker layers
      #   uses: actions/cache@v4
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile', '**/go.sum', '**/go.mod') }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-   
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: anupamdevops
          password: anuPAM666***

      - name: registry image cache
        env:
          DOCKER_BUILDKIT: 1
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: anupamdevops
          password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
          image_name: anupamdevops/myapp
          tag: cache

      
      - name: Build Docker image with static tag
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile
          push: false
          tags: anupamdevops/myapp:1
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max



      # - name: Tag Docker image with commit hash
      #   run: |
      #     COMMIT_HASH=$(git rev-parse --short HEAD)
      #     docker tag myapp:latest myapp:${COMMIT_HASH}

      # - name: Build Docker image with cached layers
      #   uses: docker/build-push-action@v5.3.0
      #   with:
      #     context: .
      #     file: Dockerfile
      #     push: false
      #     tags: myapp:latest
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
