name: cache_6
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image with Cached Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Cache Go modules
        id: cache-go-mod
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Cache Go build
        id: cache-go-build
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/*.go', '**/go.mod', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Install dependencies
        run: go mod download

      # This step builds the Go application with the necessary environment variables
      - name: Build the application
        run: |
          mkdir -p build
          CGO_ENABLED=0 GOOS=linux go build -o build/myapp .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile_1
          push: false
          tags: myapp:latest

      - name: Replace old cache with new cache
        if: success()
        run: |
          rm -rf ~/.cache/go-build
          mv ~/.cache/go-build-new ~/.cache/go-build
