name: cache
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - develop
  #   paths-ignore:
  #     - '.github/**'
  #     - '*.md'

jobs:
  build:
    name: Build Docker Image with Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/.buildx-cache
          # key: ${{ runner.os }}-buildx-${{ github.sha }}
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Install the latest buildkit release
        run: |
          BUILDKIT_URL="$(curl -sL https://api.github.com/repos/moby/buildkit/releases \
            | jq -r 'map(select((.name|startswith("v")) and (.name|contains("rc")|not)))|sort_by(.published_at)[-1].assets[]|select(.name|endswith(".linux-amd64.tar.gz")).browser_download_url')"
          curl -L "${BUILDKIT_URL}" | sudo tar -xz -C /usr/local
          
      - name: Start buildkit daemon
        run: |
          sudo --non-interactive --shell <<END_SUDO
            install -d -m 0750 -o root -g docker /run/buildkit
            buildkitd &
            while ! test -S /run/buildkit/buildkitd.sock; do sleep 0.1; done
            chgrp docker /run/buildkit/buildkitd.sock
          END_SUDO

      - name: Build Docker image
        uses: docker/build-push-action@v5.3.0
        with:
         context: .
         file: Dockerfile
         push: false
         tags: myapp:latest
         cache-from: type=local,src=/tmp/.buildx-cache
         cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
