name: cache_6
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image with Cached Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Cache Go modules
        id: cache-go-modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-modules-

      - name: Install dependencies
        run: go mod download

      - name: Build the application
        run: |
          go build -o myapp .

      - name: Cache Go binary
        uses: actions/cache@v2
        with:
          path: .  # Cache the built binary
          key: ${{ runner.os }}-go-binary-${{ hashFiles('myapp') }}
          restore-keys: ${{ runner.os }}-go-binary-
          
      - name: Build Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile_1
          push: false
          tags: myapp:latest

      - name: Replace old cache with new cache
        if: success()
        run: |
          rm -rf ~/.cache/go-build
          mv ~/.cache/go-build-new ~/.cache/go-build || true
