name: cache_1
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - develop
  #   paths-ignore:
  #     - '.github/**'
  #     - '*.md'

jobs:
  build:
    name: Build Docker Image with Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: cache docker layer
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/.buildx-cache
          # path: buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          # key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile', '**/go.sum', '**/go.mod') }}

      - name: inject layer cache into docker
        id: cache-docker-layers
        uses: reproducible-containers/buildkit-cache-dance@v2.1.3
        with:

          cache-source: /tmp/.buildx-cache
          # cache-source: buildx-cache
          cache-target: /tmp/.buildx-cache

      - name: Build Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile
          push: false
          tags: myapp:latest
          cache-from: type=gha 
          cache-to: type=gha, mode=max
