name: cache_5
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - develop
  #   paths-ignore:
  #     - '.github/**'
  #     - '*.md'

jobs:
  build:
    name: Build Docker Image with Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        with:
          install: true

      - name: Go Build Cache for Docker
        uses: actions/cache@v4
        with:
          path: go-build-cache
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}

      - name: inject go-build-cache into docker
        uses: reproducible-containers/buildkit-cache-dance@4b2444fec0c0fb9dbf175a96c094720a692ef810 # v2.1.4
        with:
          cache-source: go-build-cache


      # - name: cache docker layers
      #   uses: satackey/action-docker-layer-caching@v0.0.11

      # - name: Build Docker image
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Build Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile
          push: false
          tags: myapp:latest
          cache-from: type=gha,scope=cotainer
          cache-to: type=gha,scope=cotainer,mode=max
