name: cache_5
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3.3.0 
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3.2.0
        # with:
        #   username: anupamdevops
        #   password: "${{ secrets.DOCKER_HUB_PASSWORD }}"

      - name: registry image cache
        env:
          DOCKER_BUILDKIT: 1
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: anupamdevops
          password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
          image_name: anupamdevops/myapp
          image_tag: cache_1
          pull_image_and_stages: false



