name: cache_3
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - develop
  #   paths-ignore:
  #     - '.github/**'
  #     - '*.md'

jobs:
  build:
    name: Build Docker Image with Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        with:
          install: true

      - name: cache docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      
        # uses: docker/build-push-action@v5.3.0
        # with:
        #   context: .
        #   file: Dockerfile
        #   push: false
        #   tags: myapp:latest
        #   cache-from: type=gha,scope=cotainer
        #   cache-to: type=gha,scope=cotainer,mode=max
