name: cache
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - develop
  #   paths-ignore:
  #     - '.github/**'
  #     - '*.md'

jobs:
  build:
    name: Build Docker Image with Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Cache Docker layers
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/.buildx-cache
          # key: ${{ runner.os }}-buildx-${{ github.sha }}
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile', '**/go.sum', '**/go.mod') }}

          restore-keys: |
            ${{ runner.os }}-buildx-
            
      # - name: Docker Layer Caching
      #   uses: satackey/action-docker-layer-caching@v0.0.11
      #   with:
      #    key: docker-layer-caching-${{ github.workflow }}-{hash}
      #    restore-keys: docker-layer-caching-${{ github.workflow }}-
      #    concurrency: 3
      #    skip-save: false
          
      - name: Build Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile
          push: false
          tags: myapp:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          # cache-from: type=gha
          # cache-to: type=gha, mode=max
